# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cust',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('addrline1', models.TextField()),
                ('addrline2', models.TextField()),
                ('city', models.CharField(max_length=15)),
                ('state', models.CharField(max_length=30)),
                ('zip', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('area_code', models.IntegerField()),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
